# Tarp Data For 2023

In [47]:
# Loading all the necessary libraries
import rasterio
import rasterio.plot
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import geopandas as gpd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from patsy import dmatrices

In [48]:
# Code for analyzing tarp pixels data in format
red_tarp_folder= r"C:\Users\omkar\Box\Capstone Project\Capstone\GIS\Data\2023\FID_2"
white_tarp_folder = r"C:\Users\omkar\Box\Capstone Project\Capstone\GIS\Data\2023\FID_3"

In [126]:
red_raster_files = [os.path.join(red_tarp_folder,f) for f in os.listdir(red_tarp_folder) if f.endswith("FID2.tif")]
white_raster_files = [os.path.join(white_tarp_folder,f) for f in os.listdir(white_tarp_folder)if f.endswith("FID3.tif")]

In [50]:
print(red_raster_files)
print(white_raster_files)

['C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230509_155405_95_2402_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230510_154308_27_241c_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230510_154310_42_241c_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230511_150441_50_24b4_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230511_150443_79_24b4_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230511_153541_78_2470_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230514_145826_47_241b_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230514_150601_73_24d0_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230515_150628_99_24ca_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230516_150355_81_24b0_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230518_150532_91_24a9_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230526_145502_19_242b_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230526_145504_29_242b_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230526_150522_82_24c7_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230526_150525_09_24c7_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230527_150504_56_24af_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230527_150506_87_24af_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230528_153707_57_2488_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230528_153709_77_2488_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230528_154156_02_227a_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230529_145632_37_2442_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230529_145634_46_2442_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230530_145908_56_2427_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230530_154151_28_241c_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230531_153016_26_2251_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230602_153716_50_2489_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230615_154111_91_247f_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230711_150213_27_241f_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230726_154050_48_249a_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230806_150054_80_241e_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230806_154014_22_2478_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230806_154016_34_2478_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230820_154308_29_248c_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230822_143938_04_2445_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230822_154038_46_247c_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230831_154216_12_2486_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230902_154542_28_249a_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230903_154342_55_248e_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230922_145845_34_2455_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230922_145847_40_2455_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20230928_154406_88_227a_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20231001_150447_66_24c5_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20231004_154448_05_2488_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20231004_154450_15_2488_3B_AnalyticMS_SR_clip_FID2.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_2\\20231005_150627_37_24b3_3B_AnalyticMS_SR_clip_FID2.tif']
['C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230509_155405_95_2402_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230510_154308_27_241c_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230510_154310_42_241c_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230511_150441_50_24b4_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230511_150443_79_24b4_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230511_153541_78_2470_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230514_145826_47_241b_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230514_150601_73_24d0_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230515_150628_99_24ca_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230516_150355_81_24b0_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230518_150532_91_24a9_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230526_145502_19_242b_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230526_145504_29_242b_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230526_150522_82_24c7_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230526_150525_09_24c7_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230527_150504_56_24af_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230527_150506_87_24af_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230528_153707_57_2488_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230528_153709_77_2488_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230528_154156_02_227a_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230529_145632_37_2442_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230529_145634_46_2442_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230530_145908_56_2427_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230530_154151_28_241c_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230531_153016_26_2251_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230602_153716_50_2489_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230615_154111_91_247f_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230711_150213_27_241f_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230726_154050_48_249a_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230806_150054_80_241e_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230806_154014_22_2478_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230806_154016_34_2478_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230820_154308_29_248c_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230822_143938_04_2445_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230822_154038_46_247c_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230831_154216_12_2486_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230902_154542_28_249a_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230903_154342_55_248e_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230922_145845_34_2455_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230922_145847_40_2455_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20230928_154406_88_227a_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20231001_150447_66_24c5_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20231004_154448_05_2488_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20231004_154450_15_2488_3B_AnalyticMS_SR_clip_FID3.tif', 'C:\\Users\\omkar\\Box\\Capstone Project\\Capstone\\GIS\\Data\\2023\\FID_3\\20231005_150627_37_24b3_3B_AnalyticMS_SR_clip_FID3.tif']

In [ ]:
# # Loading the values of all files using rasterio
# def load_raster_values(raster_files):
#     raster_values = []
#     image_name = os.path.splitext(os.path.basename(raster_path))[0]

#     with rasterio.open(raster_files) as src:
#         band_data  = src.read()
#         raster_values.append({
#             'Raster_name': image_name,
#             'band_data': band_data
#         })
#     return raster_values

# # Load red tarp raster values
# red_tarp_values = []
# for raster_path in red_raster_files:
#     red_tarp_values.extend(load_raster_values(raster_path))

In [ ]:
# Define band names in order
band_names = ['blue', 'green', 'red', 'NIR']
# red_tarp_records = []
# for item in red_tarp_values:
#     Raster_name = item['Raster_name']  # e.g., 'rastername_pixel_1'
#     tarp_id = Raster_name.split('_')[-1]  # e.g., '1'
#     arr = item['band_data']  # shape: (bands, height, width)
#     # Flatten each band and create a dict for this pixel
#     row = {'Raster_name': Raster_name}
#     for i, band in enumerate(band_names):
#         # Flatten the band array and store as a list
#         row[f'{tarp_id}_{band}'] = arr[i].flatten().tolist()
#     red_tarp_records.append(row)

In [ ]:
# red_tarp_records

[{'Raster_name': '20230509_155405_95_2402_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 410, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 752, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1597, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4733, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230510_154308_27_241c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 624, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 896, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1488, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4672, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230510_154310_42_241c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 1011, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1140, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1572, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4712, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230511_150441_50_24b4_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 661, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 943, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1702, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4982, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230511_150443_79_24b4_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 653, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 908, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1442, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 5041, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230511_153541_78_2470_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 824, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1040, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1823, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4805, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230514_145826_47_241b_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 794, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1036, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 2000, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 5200, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230514_150601_73_24d0_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 580, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 996, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1537, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 5189, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230515_150628_99_24ca_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 747, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1096, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1571, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 5119, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230516_150355_81_24b0_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 605, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1018, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1990, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 5236, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230518_150532_91_24a9_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 714, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1024, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1638, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4750, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230526_145502_19_242b_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 673, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 963, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1209, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4497, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230526_145504_29_242b_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 853, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1190, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1249, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4554, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230526_150522_82_24c7_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 703, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1094, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1179, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4887, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230526_150525_09_24c7_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 692, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1095, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1313, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4959, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230527_150504_56_24af_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 829, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1159, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1220, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4732, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230527_150506_87_24af_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 731, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1079, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1223, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4904, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230528_153707_57_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 747, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1013, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1250, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4256, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230528_153709_77_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 727, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 996, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1196, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4223, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230528_154156_02_227a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 587, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 996, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1197, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4397, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230529_145632_37_2442_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 724, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1153, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1443, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4534, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230529_145634_46_2442_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 742, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1168, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1408, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4582, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230530_145908_56_2427_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 790, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1159, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1355, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4626, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230530_154151_28_241c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 761, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1140, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1393, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4352, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230531_153016_26_2251_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 691, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1138, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1444, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4786, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230602_153716_50_2489_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 827, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 1164, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1504, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4272, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230615_154111_91_247f_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 565, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 858, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1170, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3383, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230711_150213_27_241f_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 529, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 784, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 858, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4302, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230726_154050_48_249a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 554, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 814, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 855, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3851, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230806_150054_80_241e_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 409, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 765, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 876, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4074, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230806_154014_22_2478_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 431, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 682, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 846, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3684, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230806_154016_34_2478_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [1, 1, 1, 1, 1, 1],
  'FID2_green': [1, 1, 1, 1, 1, 1],
  'FID2_red': [1, 1, 1, 1, 1, 1],
  'FID2_NIR': [1, 1, 1, 1, 1, 1]},
 {'Raster_name': '20230820_154308_29_248c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 493, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 786, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 799, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4325, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230822_143938_04_2445_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 559, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 881, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 848, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4469, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230822_154038_46_247c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 406, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 722, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 743, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4068, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230831_154216_12_2486_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 443, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 744, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 759, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4057, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230902_154542_28_249a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 449, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 768, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 783, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3780, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230903_154342_55_248e_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 374, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 754, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 854, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3859, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230922_145845_34_2455_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 463, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 805, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 808, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4451, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230922_145847_40_2455_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 440, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 826, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 759, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4604, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20230928_154406_88_227a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 513, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 848, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 849, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4104, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20231001_150447_66_24c5_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 466, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 725, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 993, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 4002, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20231004_154448_05_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 375, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 704, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 920, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3871, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20231004_154450_15_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 446, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 803, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 878, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3875, 65535, 65535, 65535, 65535]},
 {'Raster_name': '20231005_150627_37_24b3_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': [65535, 558, 65535, 65535, 65535, 65535],
  'FID2_green': [65535, 882, 65535, 65535, 65535, 65535],
  'FID2_red': [65535, 1050, 65535, 65535, 65535, 65535],
  'FID2_NIR': [65535, 3772, 65535, 65535, 65535, 65535]}]

In [ ]:
# # Filter out 65535 values from each band list in red_tarp_records
# band_keys = ['FID2_blue', 'FID2_green', 'FID2_red', 'FID2_NIR']
# def filter_band_values(record, band_keys):
#     filtered_records = []
#     for x in record:
#         for key in band_keys:
#             x[key] = x[key][1]
#         filtered_records.append(x)
#     return filtered_records

In [ ]:
# for x in red_tarp_records:
#     for key in band_keys:
#         x[key] = x[key][1]
#     print(x)

# red_tarp_records_filtered = filter_band_values(red_tarp_records, band_keys)

In [ ]:
# red_tarp_records_filtered

[{'Raster_name': '20230509_155405_95_2402_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 410,
  'FID2_green': 752,
  'FID2_red': 1597,
  'FID2_NIR': 4733},
 {'Raster_name': '20230510_154308_27_241c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 624,
  'FID2_green': 896,
  'FID2_red': 1488,
  'FID2_NIR': 4672},
 {'Raster_name': '20230510_154310_42_241c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 1011,
  'FID2_green': 1140,
  'FID2_red': 1572,
  'FID2_NIR': 4712},
 {'Raster_name': '20230511_150441_50_24b4_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 661,
  'FID2_green': 943,
  'FID2_red': 1702,
  'FID2_NIR': 4982},
 {'Raster_name': '20230511_150443_79_24b4_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 653,
  'FID2_green': 908,
  'FID2_red': 1442,
  'FID2_NIR': 5041},
 {'Raster_name': '20230511_153541_78_2470_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 824,
  'FID2_green': 1040,
  'FID2_red': 1823,
  'FID2_NIR': 4805},
 {'Raster_name': '20230514_145826_47_241b_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 794,
  'FID2_green': 1036,
  'FID2_red': 2000,
  'FID2_NIR': 5200},
 {'Raster_name': '20230514_150601_73_24d0_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 580,
  'FID2_green': 996,
  'FID2_red': 1537,
  'FID2_NIR': 5189},
 {'Raster_name': '20230515_150628_99_24ca_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 747,
  'FID2_green': 1096,
  'FID2_red': 1571,
  'FID2_NIR': 5119},
 {'Raster_name': '20230516_150355_81_24b0_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 605,
  'FID2_green': 1018,
  'FID2_red': 1990,
  'FID2_NIR': 5236},
 {'Raster_name': '20230518_150532_91_24a9_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 714,
  'FID2_green': 1024,
  'FID2_red': 1638,
  'FID2_NIR': 4750},
 {'Raster_name': '20230526_145502_19_242b_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 673,
  'FID2_green': 963,
  'FID2_red': 1209,
  'FID2_NIR': 4497},
 {'Raster_name': '20230526_145504_29_242b_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 853,
  'FID2_green': 1190,
  'FID2_red': 1249,
  'FID2_NIR': 4554},
 {'Raster_name': '20230526_150522_82_24c7_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 703,
  'FID2_green': 1094,
  'FID2_red': 1179,
  'FID2_NIR': 4887},
 {'Raster_name': '20230526_150525_09_24c7_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 692,
  'FID2_green': 1095,
  'FID2_red': 1313,
  'FID2_NIR': 4959},
 {'Raster_name': '20230527_150504_56_24af_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 829,
  'FID2_green': 1159,
  'FID2_red': 1220,
  'FID2_NIR': 4732},
 {'Raster_name': '20230527_150506_87_24af_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 731,
  'FID2_green': 1079,
  'FID2_red': 1223,
  'FID2_NIR': 4904},
 {'Raster_name': '20230528_153707_57_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 747,
  'FID2_green': 1013,
  'FID2_red': 1250,
  'FID2_NIR': 4256},
 {'Raster_name': '20230528_153709_77_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 727,
  'FID2_green': 996,
  'FID2_red': 1196,
  'FID2_NIR': 4223},
 {'Raster_name': '20230528_154156_02_227a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 587,
  'FID2_green': 996,
  'FID2_red': 1197,
  'FID2_NIR': 4397},
 {'Raster_name': '20230529_145632_37_2442_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 724,
  'FID2_green': 1153,
  'FID2_red': 1443,
  'FID2_NIR': 4534},
 {'Raster_name': '20230529_145634_46_2442_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 742,
  'FID2_green': 1168,
  'FID2_red': 1408,
  'FID2_NIR': 4582},
 {'Raster_name': '20230530_145908_56_2427_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 790,
  'FID2_green': 1159,
  'FID2_red': 1355,
  'FID2_NIR': 4626},
 {'Raster_name': '20230530_154151_28_241c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 761,
  'FID2_green': 1140,
  'FID2_red': 1393,
  'FID2_NIR': 4352},
 {'Raster_name': '20230531_153016_26_2251_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 691,
  'FID2_green': 1138,
  'FID2_red': 1444,
  'FID2_NIR': 4786},
 {'Raster_name': '20230602_153716_50_2489_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 827,
  'FID2_green': 1164,
  'FID2_red': 1504,
  'FID2_NIR': 4272},
 {'Raster_name': '20230615_154111_91_247f_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 565,
  'FID2_green': 858,
  'FID2_red': 1170,
  'FID2_NIR': 3383},
 {'Raster_name': '20230711_150213_27_241f_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 529,
  'FID2_green': 784,
  'FID2_red': 858,
  'FID2_NIR': 4302},
 {'Raster_name': '20230726_154050_48_249a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 554,
  'FID2_green': 814,
  'FID2_red': 855,
  'FID2_NIR': 3851},
 {'Raster_name': '20230806_150054_80_241e_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 409,
  'FID2_green': 765,
  'FID2_red': 876,
  'FID2_NIR': 4074},
 {'Raster_name': '20230806_154014_22_2478_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 431,
  'FID2_green': 682,
  'FID2_red': 846,
  'FID2_NIR': 3684},
 {'Raster_name': '20230806_154016_34_2478_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 1,
  'FID2_green': 1,
  'FID2_red': 1,
  'FID2_NIR': 1},
 {'Raster_name': '20230820_154308_29_248c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 493,
  'FID2_green': 786,
  'FID2_red': 799,
  'FID2_NIR': 4325},
 {'Raster_name': '20230822_143938_04_2445_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 559,
  'FID2_green': 881,
  'FID2_red': 848,
  'FID2_NIR': 4469},
 {'Raster_name': '20230822_154038_46_247c_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 406,
  'FID2_green': 722,
  'FID2_red': 743,
  'FID2_NIR': 4068},
 {'Raster_name': '20230831_154216_12_2486_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 443,
  'FID2_green': 744,
  'FID2_red': 759,
  'FID2_NIR': 4057},
 {'Raster_name': '20230902_154542_28_249a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 449,
  'FID2_green': 768,
  'FID2_red': 783,
  'FID2_NIR': 3780},
 {'Raster_name': '20230903_154342_55_248e_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 374,
  'FID2_green': 754,
  'FID2_red': 854,
  'FID2_NIR': 3859},
 {'Raster_name': '20230922_145845_34_2455_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 463,
  'FID2_green': 805,
  'FID2_red': 808,
  'FID2_NIR': 4451},
 {'Raster_name': '20230922_145847_40_2455_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 440,
  'FID2_green': 826,
  'FID2_red': 759,
  'FID2_NIR': 4604},
 {'Raster_name': '20230928_154406_88_227a_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 513,
  'FID2_green': 848,
  'FID2_red': 849,
  'FID2_NIR': 4104},
 {'Raster_name': '20231001_150447_66_24c5_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 466,
  'FID2_green': 725,
  'FID2_red': 993,
  'FID2_NIR': 4002},
 {'Raster_name': '20231004_154448_05_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 375,
  'FID2_green': 704,
  'FID2_red': 920,
  'FID2_NIR': 3871},
 {'Raster_name': '20231004_154450_15_2488_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 446,
  'FID2_green': 803,
  'FID2_red': 878,
  'FID2_NIR': 3875},
 {'Raster_name': '20231005_150627_37_24b3_3B_AnalyticMS_SR_clip_FID2',
  'FID2_blue': 558,
  'FID2_green': 882,
  'FID2_red': 1050,
  'FID2_NIR': 3772}]

In [130]:
# Loading the values of all files using rasterio
def tarp_raster_to_dataframe(raster_files,band_names):
    raster_values = []
    for raster_path in raster_files:
        image_name = os.path.splitext(os.path.basename(raster_path))[0]

        with rasterio.open(raster_path) as src:
            band_data  = src.read()
            raster_values.append({
                'Raster_name': image_name,
                'band_data': band_data
            })



# Define band names in order
# band_names = ['blue', 'green', 'red', 'NIR']
    raster_tarp_records = []
    for item in raster_values:
        Raster_name = item['Raster_name']  # e.g., 'rastername_pixel_1'
        tarp_id = Raster_name.split('_')[-1]  # e.g., '1'
        arr = item['band_data']  # shape: (bands, height, width)
        # Flatten each band and create a dict for this pixel
        row = {'Raster_name': Raster_name}
        for i, band in enumerate(band_names):
            # Flatten the band array and store as a list
            row[f'{tarp_id}_{band}'] = arr[i].flatten().tolist()
        raster_tarp_records.append(row)


    band_keys = [f"{tarp_id}_{band}" for band in band_names]

    # Filter out 65535 values from each band list in red_tarp_records
    # band_keys = ['FID2_blue', 'FID2_green', 'FID2_red', 'FID2_NIR']
    filtered_records = []
    for x in raster_tarp_records:
        for key in band_keys:
            x[key] = x[key][1]
        filtered_records.append(x)
    # Convert to DataFrame
    filtered_records = pd.DataFrame(filtered_records)
    return filtered_records

In [131]:
df_red_tarp = tarp_raster_to_dataframe(red_raster_files, band_names)
df_white_tarp = tarp_raster_to_dataframe(white_raster_files, band_names)

In [132]:
df_red_tarp

,Raster_name,FID2_blue,FID2_green,FID2_red,FID2_NIR
0,20230509_155405_95_2402_3B_AnalyticMS_SR_clip_...,410,752,1597,4733
1,20230510_154308_27_241c_3B_AnalyticMS_SR_clip_...,624,896,1488,4672
2,20230510_154310_42_241c_3B_AnalyticMS_SR_clip_...,1011,1140,1572,4712
3,20230511_150441_50_24b4_3B_AnalyticMS_SR_clip_...,661,943,1702,4982
4,20230511_150443_79_24b4_3B_AnalyticMS_SR_clip_...,653,908,1442,5041
5,20230511_153541_78_2470_3B_AnalyticMS_SR_clip_...,824,1040,1823,4805
6,20230514_145826_47_241b_3B_AnalyticMS_SR_clip_...,794,1036,2000,5200
7,20230514_150601_73_24d0_3B_AnalyticMS_SR_clip_...,580,996,1537,5189
8,20230515_150628_99_24ca_3B_AnalyticMS_SR_clip_...,747,1096,1571,5119
9,20230516_150355_81_24b0_3B_AnalyticMS_SR_clip_...,605,1018,1990,5236
10,20230518_150532_91_24a9_3B_AnalyticMS_SR_clip_...,714,1024,1638,4750
11,20230526_145502_19_242b_3B_AnalyticMS_SR_clip_...,673,963,1209,4497
12,20230526_145504_29_242b_3B_AnalyticMS_SR_clip_...,853,1190,1249,4554
13,20230526_150522_82_24c7_3B_AnalyticMS_SR_clip_...,703,1094,1179,4887
14,20230526_150525_09_24c7_3B_AnalyticMS_SR_clip_...,692,1095,1313,4959
15,20230527_150504_56_24af_3B_AnalyticMS_SR_clip_...,829,1159,1220,4732
16,20230527_150506_87_24af_3B_AnalyticMS_SR_clip_...,731,1079,1223,4904
17,20230528_153707_57_2488_3B_AnalyticMS_SR_clip_...,747,1013,1250,4256
18,20230528_153709_77_2488_3B_AnalyticMS_SR_clip_...,727,996,1196,4223
19,20230528_154156_02_227a_3B_AnalyticMS_SR_clip_...,587,996,1197,4397
20,20230529_145632_37_2442_3B_AnalyticMS_SR_clip_...,724,1153,1443,4534
21,20230529_145634_46_2442_3B_AnalyticMS_SR_clip_...,742,1168,1408,4582
22,20230530_145908_56_2427_3B_AnalyticMS_SR_clip_...,790,1159,1355,4626
23,20230530_154151_28_241c_3B_AnalyticMS_SR_clip_...,761,1140,1393,4352
24,20230531_153016_26_2251_3B_AnalyticMS_SR_clip_...,691,1138,1444,4786
25,20230602_153716_50_2489_3B_AnalyticMS_SR_clip_...,827,1164,1504,4272
26,20230615_154111_91_247f_3B_AnalyticMS_SR_clip_...,565,858,1170,3383
27,20230711_150213_27_241f_3B_AnalyticMS_SR_clip_...,529,784,858,4302
28,20230726_154050_48_249a_3B_AnalyticMS_SR_clip_...,554,814,855,3851
29,20230806_150054_80_241e_3B_AnalyticMS_SR_clip_...,409,765,876,4074
30,20230806_154014_22_2478_3B_AnalyticMS_SR_clip_...,431,682,846,3684
31,20230806_154016_34_2478_3B_AnalyticMS_SR_clip_...,1,1,1,1
32,20230820_154308_29_248c_3B_AnalyticMS_SR_clip_...,493,786,799,4325
33,20230822_143938_04_2445_3B_AnalyticMS_SR_clip_...,559,881,848,4469
34,20230822_154038_46_247c_3B_AnalyticMS_SR_clip_...,406,722,743,4068
35,20230831_154216_12_2486_3B_AnalyticMS_SR_clip_...,443,744,759,4057
36,20230902_154542_28_249a_3B_AnalyticMS_SR_clip_...,449,768,783,3780
37,20230903_154342_55_248e_3B_AnalyticMS_SR_clip_...,374,754,854,3859
38,20230922_145845_34_2455_3B_AnalyticMS_SR_clip_...,463,805,808,4451
39,20230922_145847_40_2455_3B_AnalyticMS_SR_clip_...,440,826,759,4604
40,20230928_154406_88_227a_3B_AnalyticMS_SR_clip_...,513,848,849,4104
41,20231001_150447_66_24c5_3B_AnalyticMS_SR_clip_...,466,725,993,4002
42,20231004_154448_05_2488_3B_AnalyticMS_SR_clip_...,375,704,920,3871
43,20231004_154450_15_2488_3B_AnalyticMS_SR_clip_...,446,803,878,3875
44,20231005_150627_37_24b3_3B_AnalyticMS_SR_clip_...,558,882,1050,3772

In [133]:
df_white_tarp

,Raster_name,FID3_blue,FID3_green,FID3_red,FID3_NIR
0,20230509_155405_95_2402_3B_AnalyticMS_SR_clip_...,1540,1823,1926,4679
1,20230510_154308_27_241c_3B_AnalyticMS_SR_clip_...,1940,1840,2043,4862
2,20230510_154310_42_241c_3B_AnalyticMS_SR_clip_...,1283,1415,1607,4764
3,20230511_150441_50_24b4_3B_AnalyticMS_SR_clip_...,1867,2243,2147,5082
4,20230511_150443_79_24b4_3B_AnalyticMS_SR_clip_...,1886,2499,2180,5268
5,20230511_153541_78_2470_3B_AnalyticMS_SR_clip_...,1570,1646,1951,4954
6,20230514_145826_47_241b_3B_AnalyticMS_SR_clip_...,1780,2145,2286,5255
7,20230514_150601_73_24d0_3B_AnalyticMS_SR_clip_...,1959,2595,2261,5574
8,20230515_150628_99_24ca_3B_AnalyticMS_SR_clip_...,1783,2439,2250,5382
9,20230516_150355_81_24b0_3B_AnalyticMS_SR_clip_...,1844,2734,2571,5503
10,20230518_150532_91_24a9_3B_AnalyticMS_SR_clip_...,1415,2154,1978,5103
11,20230526_145502_19_242b_3B_AnalyticMS_SR_clip_...,1246,1593,1718,4608
12,20230526_145504_29_242b_3B_AnalyticMS_SR_clip_...,1268,1670,1544,4858
13,20230526_150522_82_24c7_3B_AnalyticMS_SR_clip_...,1056,2026,1814,5097
14,20230526_150525_09_24c7_3B_AnalyticMS_SR_clip_...,1028,2038,1669,4955
15,20230527_150504_56_24af_3B_AnalyticMS_SR_clip_...,1552,2219,2095,5300
16,20230527_150506_87_24af_3B_AnalyticMS_SR_clip_...,1549,2023,1944,5260
17,20230528_153707_57_2488_3B_AnalyticMS_SR_clip_...,1499,2009,2005,4539
18,20230528_153709_77_2488_3B_AnalyticMS_SR_clip_...,1494,2003,1981,4486
19,20230528_154156_02_227a_3B_AnalyticMS_SR_clip_...,1719,2021,2092,4693
20,20230529_145632_37_2442_3B_AnalyticMS_SR_clip_...,1705,1991,2022,4771
21,20230529_145634_46_2442_3B_AnalyticMS_SR_clip_...,1767,2047,2083,4726
22,20230530_145908_56_2427_3B_AnalyticMS_SR_clip_...,1888,2171,2193,5020
23,20230530_154151_28_241c_3B_AnalyticMS_SR_clip_...,1888,2333,2342,4931
24,20230531_153016_26_2251_3B_AnalyticMS_SR_clip_...,1857,2063,2315,5036
25,20230602_153716_50_2489_3B_AnalyticMS_SR_clip_...,2262,2305,2615,4982
26,20230615_154111_91_247f_3B_AnalyticMS_SR_clip_...,2049,2182,2209,3657
27,20230711_150213_27_241f_3B_AnalyticMS_SR_clip_...,1212,1514,1418,4559
28,20230726_154050_48_249a_3B_AnalyticMS_SR_clip_...,1218,1382,1473,3953
29,20230806_150054_80_241e_3B_AnalyticMS_SR_clip_...,1462,1786,1748,4300
30,20230806_154014_22_2478_3B_AnalyticMS_SR_clip_...,1650,1879,1885,3809
31,20230806_154016_34_2478_3B_AnalyticMS_SR_clip_...,1,1,1,1
32,20230820_154308_29_248c_3B_AnalyticMS_SR_clip_...,1293,1574,1636,4427
33,20230822_143938_04_2445_3B_AnalyticMS_SR_clip_...,1400,1677,1499,4522
34,20230822_154038_46_247c_3B_AnalyticMS_SR_clip_...,1172,1540,1368,4190
35,20230831_154216_12_2486_3B_AnalyticMS_SR_clip_...,1494,1749,1663,4354
36,20230902_154542_28_249a_3B_AnalyticMS_SR_clip_...,1227,1651,1572,3923
37,20230903_154342_55_248e_3B_AnalyticMS_SR_clip_...,1259,1456,1440,3952
38,20230922_145845_34_2455_3B_AnalyticMS_SR_clip_...,1166,1318,1256,4735
39,20230922_145847_40_2455_3B_AnalyticMS_SR_clip_...,1311,1434,1464,4721
40,20230928_154406_88_227a_3B_AnalyticMS_SR_clip_...,993,1269,1211,4090
41,20231001_150447_66_24c5_3B_AnalyticMS_SR_clip_...,827,1247,1086,4218
42,20231004_154448_05_2488_3B_AnalyticMS_SR_clip_...,1199,1456,1394,3964
43,20231004_154450_15_2488_3B_AnalyticMS_SR_clip_...,1224,1550,1484,4059
44,20231005_150627_37_24b3_3B_AnalyticMS_SR_clip_...,1274,1415,1331,3819

In [134]:

df_red_tarp.to_csv(r'D:\Capstone\Data\2023\red_tarp_pixel_band_values.csv')
df_white_tarp.to_csv(r'D:\Capstone\Data\2023\white_tarp_pixel_band_values.csv')