In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols
from patsy import dmatrices
import numpy as np
import os
import rasterio
import pandas as pd

In [14]:
df_pixel_2 = pd.read_excel(r"D:\Capstone\EDA\transformed_poster_data_with_dap_column.xlsx")

In [15]:
df_pixel_2.head()

,date_pixel_2,pixel_2_red,pixel_2_nir,red_tarp_red,red_tarp_nir,white_tarp_red,white_tarp_nir,date_pixel_2_cleaned,datetime_pixel_2,date,dap
0,20230516,1777,2997,1990,5236,2571,5503,20230516,2023-05-16,2023-05-16,0
1,20230518,1520,2927,1638,4750,1978,5103,20230518,2023-05-18,2023-05-18,2
2,20230526,1561,2898,1209,4497,1718,4608,20230526,2023-05-26,2023-05-26,10
3,20230526,1538,2886,1249,4554,1544,4858,20230526,2023-05-26,2023-05-26,10
4,20230526,1541,2939,1179,4887,1814,5097,20230526,2023-05-26,2023-05-26,10

In [16]:
df_pixel_2['p2_red_minus_rt_red'] = df_pixel_2['pixel_2_red'] - df_pixel_2['red_tarp_red']
df_pixel_2['p2_nir_minus_rt_nir'] = df_pixel_2['pixel_2_nir'] - df_pixel_2['red_tarp_nir']
df_pixel_2['p2_red_minus_wt_red'] = df_pixel_2['pixel_2_red'] - df_pixel_2['white_tarp_red']
df_pixel_2['p2_nir_minus_wt_nir'] = df_pixel_2['pixel_2_nir'] - df_pixel_2['white_tarp_nir']

In [17]:
df_pixel_2["rt_band_cor_ndvi"] = (df_pixel_2['p2_nir_minus_rt_nir'] - df_pixel_2['p2_red_minus_rt_red']) / (df_pixel_2['p2_nir_minus_rt_nir'] + df_pixel_2['p2_red_minus_rt_red'])
df_pixel_2["wt_band_cor_ndvi"] = (df_pixel_2['p2_nir_minus_wt_nir'] - df_pixel_2['p2_red_minus_wt_red']) / (df_pixel_2['p2_nir_minus_wt_nir'] + df_pixel_2['p2_red_minus_wt_red'])

In [18]:
df_pixel_2

,date_pixel_2,pixel_2_red,pixel_2_nir,red_tarp_red,red_tarp_nir,white_tarp_red,white_tarp_nir,date_pixel_2_cleaned,datetime_pixel_2,date,dap,p2_red_minus_rt_red,p2_nir_minus_rt_nir,p2_red_minus_wt_red,p2_nir_minus_wt_nir,rt_band_cor_ndvi,wt_band_cor_ndvi
0,20230516,1777,2997,1990,5236,2571,5503,20230516,2023-05-16,2023-05-16,0,-213,-2239,-794,-2506,0.826264,0.518788
1,20230518,1520,2927,1638,4750,1978,5103,20230518,2023-05-18,2023-05-18,2,-118,-1823,-458,-2176,0.878413,0.652240
2,20230526,1561,2898,1209,4497,1718,4608,20230526,2023-05-26,2023-05-26,10,352,-1599,-157,-1710,1.564555,0.831816
3,20230526,1538,2886,1249,4554,1544,4858,20230526,2023-05-26,2023-05-26,10,289,-1668,-6,-1972,1.419144,0.993933
4,20230526,1541,2939,1179,4887,1814,5097,20230526,2023-05-26,2023-05-26,10,362,-1948,-273,-2158,1.456494,0.775401
5,20230526,1542,2897,1313,4959,1669,4955,20230526,2023-05-26,2023-05-26,10,229,-2062,-127,-2058,1.249864,0.883753
6,20230527,1551,3003,1220,4732,2095,5300,20230527,2023-05-27,2023-05-27,11,331,-1729,-544,-2297,1.473534,0.617036
7,20230527,1536,3012,1223,4904,1944,5260,20230527,2023-05-27,2023-05-27,11,313,-1892,-408,-2248,1.396453,0.692771
8,20230528,1495,2755,1250,4256,2005,4539,20230528,2023-05-28,2023-05-28,12,245,-1501,-510,-1784,1.390127,0.555362
9,20230528,1480,2840,1196,4223,1981,4486,20230528,2023-05-28,2023-05-28,12,284,-1383,-501,-1646,1.516833,0.533302
10,20230528,1510,2808,1197,4397,2092,4693,20230528,2023-05-28,2023-05-28,12,313,-1589,-582,-1885,1.490596,0.528172
11,20230529,1663,2829,1443,4534,2022,4771,20230529,2023-05-29,2023-05-29,13,220,-1705,-359,-1942,1.296296,0.687962
12,20230529,1614,2922,1408,4582,2083,4726,20230529,2023-05-29,2023-05-29,13,206,-1660,-469,-1804,1.283356,0.587330
13,20230530,1686,3102,1355,4626,2193,5020,20230530,2023-05-30,2023-05-30,14,331,-1524,-507,-1918,1.554904,0.581856
14,20230530,1590,2844,1393,4352,2342,4931,20230530,2023-05-30,2023-05-30,14,197,-1508,-752,-2087,1.300534,0.470236
15,20230531,1565,3114,1444,4786,2315,5036,20230531,2023-05-31,2023-05-31,15,121,-1672,-750,-1922,1.156028,0.438623
16,20230602,1732,2854,1504,4272,2615,4982,20230602,2023-06-02,2023-06-02,17,228,-1418,-883,-2128,1.383193,0.413484
17,20230615,758,2134,1170,3383,2209,3657,20230615,2023-06-15,2023-06-15,30,-412,-1249,-1451,-1523,0.503913,0.024210
18,20230711,380,4254,858,4302,1418,4559,20230711,2023-07-11,2023-07-11,56,-478,-48,-1038,-305,-0.817490,-0.545793
19,20230726,431,4412,855,3851,1473,3953,20230726,2023-07-26,2023-07-26,71,-424,561,-1042,459,7.189781,-2.574614
20,20230806,456,4888,876,4074,1748,4300,20230806,2023-08-06,2023-08-06,82,-420,814,-1292,588,3.131980,-2.670455
21,20230806,391,4631,846,3684,1885,3809,20230806,2023-08-06,2023-08-06,82,-455,947,-1494,822,2.849593,-3.446429
22,20230820,464,4644,799,4325,1636,4427,20230820,2023-08-20,2023-08-20,96,-335,319,-1172,217,-40.875000,-1.454450
23,20230822,486,4658,848,4469,1499,4522,20230822,2023-08-22,2023-08-22,98,-362,189,-1013,136,-3.184971,-1.310148
24,20230822,414,4338,743,4068,1368,4190,20230822,2023-08-22,2023-08-22,98,-329,270,-954,148,-10.152542,-1.367246
25,20230831,375,4431,759,4057,1663,4354,20230831,2023-08-31,2023-08-31,107,-384,374,-1288,77,-75.800000,-1.127168
26,20230902,498,4122,783,3780,1572,3923,20230902,2023-09-02,2023-09-02,109,-285,342,-1074,199,11.000000,-1.454857
27,20230903,381,4308,854,3859,1440,3952,20230903,2023-09-03,2023-09-03,110,-473,449,-1059,356,-38.416667,-2.012802
28,20230922,555,4388,808,4451,1256,4735,20230922,2023-09-22,2023-09-22,129,-253,-63,-701,-347,-0.601266,-0.337786
29,20230922,593,4242,759,4604,1464,4721,20230922,2023-09-22,2023-09-22,129,-166,-362,-871,-479,0.371212,-0.290370
30,20230928,708,3588,849,4104,1211,4090,20230928,2023-09-28,2023-09-28,135,-141,-516,-503,-502,0.570776,-0.000995
31,20231001,685,3412,993,4002,1086,4218,20231001,2023-10-01,2023-10-01,138,-308,-590,-401,-806,0.314031,0.335543
32,20231004,745,2772,920,3871,1394,3964,20231004,2023-10-04,2023-10-04,141,-175,-1099,-649,-1192,0.725275,0.294948
33,20231004,742,2742,878,3875,1484,4059,20231004,2023-10-04,2023-10-04,141,-136,-1133,-742,-1317,0.785658,0.279262
34,20231005,955,2788,1050,3772,1331,3819,20231005,2023-10-05,2023-10-05,142,-95,-984,-376,-1031,0.823911,0.465529